<?php

/**
 * @file
 * Contains hook implementations and helper functions for GSB CMSI Test
 */

/**
 * Implements hook_menu().
 */
function gsb_cmis_menu() {
  $items = array();
  $items['gsb-cmis/%gsb_cmis_content_type_import/%'] = array(
    'title' => 'GSB CMIS Content Type Import',
    'description' => 'GSB CMIS Content Type Import.',
    'page callback' => 'gsb_cmis_content_type_import',
    'page arguments' => array(1,2),
    'access arguments' => array(1),
    'access callback' => 'gsb_cmis_content_type_import_access',
  );
  $items['gsb-cmis/gsb-cmis-get-alfresco-doc/%node/%'] = array(
    'title' => 'Downloading document...',
    'description' => 'Downloading document...',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsb_cmis_get_alfresco_doc', 2, 3),
    'access callback' => TRUE,
  );
  $items['gsb-cmis/gsb-cmis-download-doc/%node/%'] = array(
    'title' => 'GSB CMIS Download Document',
    'description' => 'GSB CMIS Download Document',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsb_cmis_download_doc', 2, 3),
    'access callback' => TRUE,
  );
  $items['gsb-cmis/gsb-cmis-download-auth/%node'] = array(
    'title' => 'GSB CMIS Download Auth',
    'description' => 'GSB CMIS Download Auth',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsb_cmis_download_auth',2),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 *
 */
function gsb_cmis_content_type_import_access($content_type) {
  $token_key = variable_get('gsb_cmis_content_type_import_token', '');
  if (!empty($_GET['token']) && !empty($token_key) && $_GET['token'] == $token_key) {
    return TRUE;
  }
  return FALSE;
}

/**
 *
 */
function gsb_cmis_content_type_import_load($content_type) {
  $content_type = str_replace("working-paper", "working_paper", $content_type);
  if ($content_type != 'case' && $content_type != 'working_paper') {
    return FALSE;
  }
  $info = module_invoke_all('gsb_cmis_content_type_import_info');
  return $info[$content_type];
}

/**
 *
 */
function gsb_cmis_content_type_import($process_info, $uuid) {
  $doc = gsb_cmis_api_getDocumentObject('default', $uuid);
  $process_info['callback']($doc, $uuid);
  return 'gsb_cmis_content_type_import complete';
}

/**
 *
 */
function gsb_cmis_content_type_initial_import($content_type, $uuid) {

  if ($content_type != 'case' && $content_type != 'working_paper') {
    return FALSE;
  }

  $info = module_invoke_all('gsb_cmis_content_type_import_info');

  // get top-level folder documents

  $start_time = time_mark();
  $docs = gsb_cmis_api_getTopLevelFolders('default', $uuid);
  drush_log(dt('top level count of docs = '. count($docs)), 'success');
  time_message('time = ', $start_time, time_mark());

  foreach ($docs as $doc) {
    drush_log(dt('top-level folder uuid = '.$doc->uuid), 'success');
    $doc_ids[] = $doc->uuid;
  }

  // get top-level non folder documents

  drush_log(dt('-------------------------------'), 'success');

  $start_time = time_mark();
  $other_subdocs = _gsb_cmis_api_getTopLevelObjects('default', $uuid);
  drush_log(dt('additional top-level docs count = '.count($other_subdocs)), 'success');
  time_message('additional top-level docs - time = ', $start_time, time_mark());
  drush_log(dt('-------------------------------'), 'success');

  foreach ($other_subdocs as $doc) {
    drush_log(dt('top-level non folder uuid = '.$doc->uuid), 'success');
  }

  // process top-level folder documents

  drush_log(dt('-------------------------------'), 'success');

  foreach ($doc_ids as $doc_id) {

    drush_log(dt('processing uuid = '.$doc_id), 'success');

    // ITTest Folder for Working Papers
    list($working_paper_test_folder, $case_test_folder) = _gsb_cmis_getITTestfolderUUIDs();

    if ($doc_id == $working_paper_test_folder) {
      continue;
    }

    // ITTest Folder for Cases
    if ($doc_id == $case_test_folder) {
      continue;
    }

    $start_time = time_mark();
    $sub_docs = gsb_cmis_api_getDocuments('default', $doc_id);
    drush_log(dt('count of sub docs = '. count($sub_docs)), 'success');
    time_message('time = ', $start_time, time_mark());
    drush_log(dt('-------------------------------'), 'success');

    $start_time = time_mark();
    foreach ($sub_docs as $sub_doc) {
      $info[$content_type]['callback']($sub_doc, $sub_doc->uuid);
    }
    time_message('created nodes - time = ', $start_time, time_mark());
    drush_log(dt('-------------------------------'), 'success');

  }

  // process top-level non folder documents

  $start_time = time_mark();
  foreach ($other_subdocs as $sub_doc) {
    drush_log(dt('processing non folder uuid = '.$sub_doc->uuid), 'success');
    $info[$content_type]['callback']($sub_doc, $sub_doc->uuid);
  }
  time_message('created nodes - time = ', $start_time, time_mark());
  drush_log(dt('-------------------------------'), 'success');

}

/**
 *
 */
function time_mark() {
  $time = microtime();
  $time = explode(' ', $time);
  $time = $time[1] + $time[0];
  return $time;
}

/**
 *
 */
function time_message($message, $start_time, $end_time) {
  $total_time = round(($end_time - $start_time), 4);
  drush_log(dt($message.$total_time), 'success');
}

/**
 *
 */
function gsb_cmis_log($message, $type = 'notice', $error = null) {
  if (function_exists('drush_log')) {
    drush_log(dt($message), $type, $error);
  }
  elseif (function_exists('dpm')) {
    dpm($message);
  }
}

/**
 * Handles route for downloading Alfresco Docs
 */
function gsb_cmis_get_alfresco_doc($form, $form_state, $node, $authtype = '') {
  module_load_include('api.inc', 'cmis');

  if ($node == null) {
    return;
  }

  $language = $node->language;

  switch ($authtype) {
    case 'simplesaml':
      if ($node->type == 'case' && !gsb_cmis_check_simplesaml_auth($node)) {
        return;
      }
      gsb_cmis_download_alfresco_doc($node);
      break;
    case 'cas':
      if (user_is_logged_in()) {
        gsb_cmis_download_alfresco_doc($node);
      }
      break;
    case 'free':
      if (gsb_cmis_isFreeCase($node)) {
        gsb_cmis_download_alfresco_doc($node);
      }
      break;
    case 'notcase':
      if ($node->type != 'case') {
        gsb_cmis_download_alfresco_doc($node);
      }
      break;
    case 'gsbauth':
      if (gsb_cmis_check_all_auths($node)) {
        gsb_cmis_download_alfresco_doc($node);
      }
      break;
  }

  return $form;
}

/**
 * Streams doc from Alfresco
 */
function gsb_cmis_download_alfresco_doc($node) {
  module_load_include('api.inc', 'cmis');

  if ($node == null) {
    return;
  }

  $language = $node->language;

  $uuid = $node->field_document_uuid[$language][0]['value'];

  // get the repository and object

  $repository_name = 'default';
  $repository = cmis_get_repository($repository_name);

  try {
    // get the object with the given uuid
    $object = gsb_cmis_api_getDocumentObject($repository_name, $uuid);
    // stream the doc
    $content = cmisapi_getContentStream($repository->repositoryId, $object->id);
  }
  catch (CMISException $e) {
    $object_not_found = strstr($e->getMessage(),'Unable to find object workspace:');
    if (!empty($object_not_found)) {
      $product_type = '';
      if (!empty($node->field_product_type[$language][0])) {
        $product_type = $node->field_product_type[$language][0]['value'];
      }
      drupal_set_message('Error - Unable to find ' . $product_type . ' document: ' . '"' . $node->title . '"', 'error');
    } else {
      cmis_error_handler('cmis_browser_content_get', $e);
    }
    return;
  }

  if (ob_get_level()) {
    ob_end_clean();
  }

  $filename = $object->properties['cmis:name'];
  $file_parts = pathinfo($filename);
  if (empty($file_parts['extension'])) {
    $filename .= '.' . _gsb_cmis_get_extension_mimetype($object->properties['cmis:contentStreamMimeType']);
  }

  drupal_add_http_header('Cache-Control', 'no-cache, must-revalidate');
  drupal_add_http_header('Content-type', $object->properties['cmis:contentStreamMimeType']);
  if ($object->properties['cmis:contentStreamMimeType'] != 'text/html') {
    drupal_add_http_header('Content-Disposition', 'attachment; filename="'. $filename .'"');
  }

  // download the doc
  print($content);

  exit();
}

/**
 *
 */
function gsb_cmis_download_auth($form, $form_state, $node = null) {

  if ($node == null) {
    return;
  }

  $language = $node->language;

  if ($node->type == 'case') {
    if (gsb_cmis_isFreeCase($node)) {
      // downloading doc message page
      $form = gsb_cmis_downloading_doc($form, $form_state, $node, 'free');
    }
    else {
      $case_access = gsb_cmis_getCaseAccess($node);
      if (gsb_cmis_check_all_auths($node)) {
        // downloading doc message page
        $form = gsb_cmis_downloading_doc($form, $form_state, $node, 'gsbauth');
      }
      else {
        if ($case_access == 'Education and Corporate use') {
          // show page with two links to do alumni cas auth or simplesaml auth
          $form['stuff'] = array(
            '#type' => 'markup',
            '#markup' =>
              '<h1 class="title">Login Selection</h1>' .
              '<div class="error-wrapper">' .
                '<p class="intro-copy">The site that you are accessing requires you to sign in.<br />Select your affiliation.</p>' .
                '<div class="case-login alumni"><a href="/gsb-cmis/gsb-cmis-download-doc/' . $node->nid . '/cas">Stanford GSB <strong>Alumni</strong></a></div>' .
                '<div class="case-login fac-student-staff"><a href="/gsb-cmis/gsb-cmis-download-doc/' . $node->nid . '/simplesaml">Stanford GSB <strong>Faculty, Students, and Staff</strong></a></div>' .
              '</div>',
          );
        }
        else {
          // downloading doc message page after simplesaml login
          $form = gsb_cmis_downloading_doc($form, $form_state, $node, 'simplesaml');
        }
      }
    }
  }
  else {
    // downloading doc message page
    $form = gsb_cmis_downloading_doc($form, $form_state, $node, 'notcase');
  }

  return $form;

}

/**
 *
 */
function gsb_cmis_download_doc($form, $form_state, $node = null, $authtype = '') {
  global $base_url;

  if ($node == null) {
    return;
  }

  $language = $node->language;

  switch ($authtype) {
    case 'simplesaml':
      // check login
      if ($node->type == 'case' && !gsb_cmis_check_simplesaml_auth($node)) {
        $form['stuff'] = array(
          '#type' => 'markup',
          '#markup' =>
            '<h1 class="title">Downloading document...</h1>' .
            '<div class="error-wrapper">' .
              '<p class="intro-copy">Access for the document requested, <i>“' . $node->title . '”</i>, is available to the GSB community only.' .
              '<br /><br /><a href="" class="close-window active">Close window</a></p>' .
            '</div>',
        );
      }
      else {
        // goto downloading doc message page
        $form = gsb_cmis_downloading_doc($form, $form_state, $node, $authtype);
      }
      break;
    case 'cas':
      $next_url = $base_url . '/' . current_path();
      $next_url = str_replace('http://', 'https://', $next_url);
      alumni_cas_auth_login($next_url);
      if (!user_is_logged_in()) {
        $form['stuff'] = array(
          '#type' => 'markup',
          '#markup' =>
            '<h1 class="title">Downloading document...</h1>' .
            '<div class="error-wrapper">' .
              '<p class="intro-copy">Access for the document requested, <i>“' . $node->title . '”</i>, is available to the GSB community only.' .
              '<br /><br /><a href="" class="close-window active">Close window</a></p>' .
            '</div>',
        );
      } else {
        // goto downloading doc message page
        $form = gsb_cmis_downloading_doc($form, $form_state, $node, $authtype);
      }
      break;
  }

  return $form;
}

/**
 *
 */
function gsb_cmis_downloading_doc($form, $form_state, $node = null, $authtype = '') {

  $form['stuff'] = array(
    '#type' => 'markup',
    '#markup' =>
      '<h1 class="title">Download ' . $node->title . '</h1>' .
      '<div class="error-wrapper">' .
        '<p class="intro-copy"><i>“' . $node->title . '”</i> will download momentarily.' .
        '<br /><br /><a href="" class="close-window active">Close this window</a> when the download is complete.</p>' .
      '</div>',
  );
  $language = $node->language;
  $uuid     = $box_file_id = "";
  $uuid     = $node->field_document_uuid[$language][0]['value'];
  $box_file_id = $node->field_instance_text[$language][0]['value'];
  if( $node->type == 'case' && $box_file_id  == "")
  $form['#attached']['js'][drupal_get_path('module', 'gsb_cmis') . '/js/gsb_cmis.js'] = array('scope' => 'footer'); 
  else if( $node->type == 'case' && $box_file_id != "")
  $form['#attached']['js'][drupal_get_path('module', 'gsb_cmis') . '/js/gsb_box.js'] = array('scope' => 'footer'); 
  else if( $node->type == 'working_paper' && substr($uuid, 0, 9 ) === "urn:uuid:")
  $form['#attached']['js'][drupal_get_path('module', 'gsb_cmis') . '/js/gsb_cmis.js'] = array('scope' => 'footer'); 
  else if( $node->type == 'working_paper' && substr($uuid, 0, 9 ) != "urn:uuid:")
  $form['#attached']['js'][drupal_get_path('module', 'gsb_cmis') . '/js/gsb_box.js'] = array('scope' => 'footer'); 
  else
  $form['#attached']['js'][drupal_get_path('module', 'gsb_cmis') . '/js/gsb_cmis.js'] = array('scope' => 'footer');
  $form['#attached']['js'][] = array(
    'type' => 'setting',
    'data' => array(
      'alfresco_document' => array(
        'nid' => $node->nid,
        'authtype' => $authtype,
      ),
    ),
  );
  return $form;
}

/**
 * Check if the node is not a 'free case' and if it isn't then...
 * Check if the user has gone thru simple saml auth and...
 * has a gsb workgroup.
 */
function gsb_cmis_check_simplesaml_auth($node) {

  $language = $node->language;

  $free_case = gsb_cmis_isFreeCase($node);

  if (!$free_case) {
    $simplesaml_auth_object = simplesaml_auth_login_check(FALSE);
    $attributes = $simplesaml_auth_object->getAttributes();
    if (empty($attributes['urn:oid:1.3.6.1.4.1.5923.1.1.1.7'])) {
      return false;
    } else {
      $workgroups = $attributes['urn:oid:1.3.6.1.4.1.5923.1.1.1.7'];
      $approved_workgroups = variable_get('gsb_cmis_approved_workgroups', array());
      $has_approved_workgroup = false;
      foreach ($approved_workgroups as $awg) {
        if (in_array($awg, $workgroups)) {
          $has_approved_workgroup = true;
          break;
        }
      }
      if (in_array('gsb-apps:nongsb_deny', $workgroups)) {
        return false;
      }
      if (!$has_approved_workgroup) {
        return false;
      }
    }
  }

  return true;
}

/**
 * Implements hook_field_extra_fields().
 */
function gsb_cmis_field_extra_fields() {
  $extra = array();
  foreach(array('case','working_paper') as $node_type) {
    $extra['node'][$node_type]['display']['gsb_cmis_download_button'] = array(
      'label' => t('GSB CMIS Download Button'),
      'description' => t('The GSB CMIS download button'),
      'weight' => 0,
    );
  }
  return $extra;
}

/**
 * Implements hook_node_view().
 */
function gsb_cmis_node_view($node, $view_mode, $langcode) {

  // If this field is not configured for this view mode, skip it.
  $fields = field_extra_fields_get_display('node', $node->type, $view_mode);
  if (empty($fields['gsb_cmis_download_button']['visible'])) {
    return;
  }

  $download_button_markup = '<div class="gsb-cmis-download-wrapper">' . '<a href="' . base_path() . 'gsb-cmis/gsb-cmis-download-auth/' . $node->nid . '" class="gsb-cmis-download-button" target="_blank">' . t('Download') . '</a>' . '</div>';
  $language = $node->language;

  // if the node is 'Case' and it has a downloadable access ($downloadable_case_access)
  // ... then add the download button to the display
  if ($node->type == 'case') {
    $case_access = gsb_cmis_getCaseAccess($node);
    $downloadable_case_access = array(
      'Free',
      'Education and Corporate use',
      'Educational use only',
      'Stanford GSB classes only, accessible'
    );
    if (in_array($case_access, $downloadable_case_access)) {
      $node->content['gsb_cmis_download_button'] = array(
        '#markup' => $download_button_markup,
      );
    }
    $webauth_case_access = array(
      'Educational use only',
      'Stanford GSB classes only, accessible'
    );
    if (in_array($case_access, $webauth_case_access)) {
      $download_button_markup = '<div class="gsb-cmis-download-wrapper">' . '<a href="' . base_path() . 'gsb-cmis/gsb-cmis-download-doc/' . $node->nid . '/simplesaml' . '" class="gsb-cmis-download-button" target="_blank">' . t('Download') . '</a>' . '</div>';
      $node->content['gsb_cmis_download_button'] = array(
        '#markup' => $download_button_markup,
      );
    }

  }

  // if the node is 'Working Paper' and 'Has PDF' is checked then...
  // add the download button to the display
  if ($node->type == 'working_paper' && !empty($node->field_has_pdf[$language][0]['value'])) {
    $node->content['gsb_cmis_download_button'] = array(
      '#markup' => $download_button_markup,
    );
  }

}

/**
 *
 */
function _gsb_cmis_getITTestfolderUUIDs() {
  module_load_include('api.inc', 'cmis');

  $repository_name = 'default';

  // get the Working Paper ITTest folder uuid

  $cache = cache_get('gsb_cmis_working_paper_ct_alfresco_folder');

  if ($cache && !empty($cache->data)) {
    $uuid_working_paper_folder_uuid = $cache->data;
  } else {
    $repository = cmis_get_repository($repository_name);
    $folderObject = cmisapi_getObjectByPath($repository->repositoryId, drupal_encode_path('/Research Papers/ITTest'));
    $objectId = $folderObject->properties['cmis:objectId'];
    $uuid_working_paper_folder_uuid = str_replace('workspace://SpacesStore/', 'urn:uuid:', $objectId);
    $expire = REQUEST_TIME + (60*60*24);
    cache_set('gsb_cmis_working_paper_ct_alfresco_folder', $uuid_working_paper_folder_uuid, 'cache', $expire);
  }

  $cache = cache_get('gsb_cmis_case_ct_alfresco_folder');

  if ($cache && !empty($cache->data)) {
    $uuid_case_folder_uuid = $cache->data;
  } else {
    $repository = cmis_get_repository($repository_name);
    $folderObject = cmisapi_getObjectByPath($repository->repositoryId, drupal_encode_path('/Case Writing/ITTest'));
    $objectId = $folderObject->properties['cmis:objectId'];
    $uuid_case_folder_uuid = str_replace('workspace://SpacesStore/', 'urn:uuid:', $objectId);
    $expire = REQUEST_TIME + (60*60*24);
    cache_set('gsb_cmis_case_ct_alfresco_folder', $uuid_case_folder_uuid, 'cache', $expire);
  }

  return array($uuid_working_paper_folder_uuid, $uuid_case_folder_uuid);
}

/**
 *
 */
function gsb_cmis_isFreeCase($node) {
  $language = $node->language;
  $free_case = false;
  $case_access = gsb_cmis_getCaseAccess($node);
  if ($case_access != '') {
    if ($case_access == 'Free') {
      $free_case = true;
    }
  }
  return $free_case;
}

/**
 * Get the Access Property setting for the node.
 */
function gsb_cmis_getCaseAccess($node) {
  $language = $node->language;
  $case_access = 'Not for distribution';
  if (!empty($node->field_case_access[$language])) {
    $case_access = $node->field_case_access[$language][0]['value'];
  }
  return $case_access;
}

/**
 *
 */
function gsb_cmis_check_all_auths($node) {
  global $user;

  $cookiestring = '';
  foreach ($_COOKIE as $key => $cookie) {
    $cookiestring .= $key .'='. urlencode($cookie) .';';
  }
  $headers = array('Cookie' => $cookiestring);
  $cas_getLogin_type_url = variable_get('cas_getLogin_type_url', '');
  $response = drupal_http_request($cas_getLogin_type_url, array('headers' => $headers));

  $case_access = gsb_cmis_getCaseAccess($node);

  if (in_array($case_access, array('Free'))) {
    return true;
  }

  $cas_case_access = array(
    'Education and Corporate use',
  );

  // is this a case that can be viewed by CAS users
  if (in_array($case_access, $cas_case_access)) {
    // check if logged in with CAS
    $pos = strpos($response->data, 'REME');
    if ($pos !== false) {
      if (user_is_logged_in()) {
        return true;
      }
    }
  }

  $webauth_case_access = array(
    'Educational use only',
    'Education and Corporate use',
    'Stanford GSB classes only, accessible'
  );

  // is this a case that can be viewed by WebAuth users
  if (in_array($case_access, $webauth_case_access)) {
    // check if logged in with WebAuth (simplesaml)
    if (simplesaml_auth_user_authenticated()) {
      return true;
    }
  }

  return false;
}

/**
 * Use this function to get extension using mimetype
 *
 * @param $mimetype
 *   The mimetype base
 *
 * @return
 *   The file extension.
 */
function _gsb_cmis_get_extension_mimetype($mimetype) {
  module_load_include('inc', 'content', 'includes/file.mimetypes');
  $mapping = file_default_mimetype_mapping();

  $extension_key = array_search($mimetype, $mapping['mimetypes']);
  $extensions = array_flip($mapping['extensions']);
  return $extensions[$extension_key];
}
